import { useState } from "react";
import { CalendarDays, FileText, MessageCircle, Send } from "lucide-react";
import { PageHeading } from "../../components/PageHeading";
import { PanelHeading } from "../../components/PanelHeading";
import type { TranslationKey } from "../../i18n";

type Translator = (key: TranslationKey) => string;
export function PatientPortal({ t }: { t: Translator }) {
  const [tab, setTab] = useState<"Overview" | "Appointments" | "Messages" | "Documents">("Overview");
  const tabs = ["Overview", "Appointments", "Messages", "Documents"] as const;
  return <><PageHeading eyebrow={t("patientPortal")} title={t("patientPortal")} detail={t("portalDetail")} /><div className="tabs portal-tabs">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>{tab === "Overview" && <div className="portal-grid"><section className="panel"><PanelHeading title={t("appointments")} detail={t("scheduleDetail")} /><div className="record-item"><div className="record-date"><CalendarDays size={18} /></div><div><strong>Follow-up consultation</strong><p>Tuesday · 09:30 · Dr. Rana Samir</p></div><span className="status confirmed">Confirmed</span></div></section><section className="panel"><PanelHeading title={t("messagesTitle")} detail={t("messagesDetail")} /><div className="record-item"><div className="record-date"><MessageCircle size={18} /></div><div><strong>Care coordinator</strong><p>{t("followupsDue")}</p></div></div></section></div>}{tab === "Appointments" && <section className="panel portal-section"><PanelHeading title={t("appointments")} detail={t("scheduleDetail")} /><div className="record-item"><div className="record-date"><CalendarDays size={18} /></div><div><strong>Follow-up consultation</strong><p>Tuesday · 09:30 · Dr. Rana Samir</p></div><span className="status confirmed">Confirmed</span></div></section>}{tab === "Messages" && <section className="panel portal-section"><PanelHeading title={t("messagesTitle")} detail={t("messagesDetail")} /><div className="message-bubble received">{t("followupsDue")}</div><div className="portal-compose"><input placeholder="Type a message" /><button className="primary-btn small"><Send size={14} /> {t("reply")}</button></div></section>}{tab === "Documents" && <section className="panel portal-section"><PanelHeading title="Documents" detail="Shared records and treatment documents" /><div className="record-item"><div className="record-date"><FileText size={18} /></div><div><strong>Recent ECG report</strong><p>Imaging · Reviewed · Today</p></div></div></section>}</>;
}
